### ISSUE TITLE
Hi. I see you id in Sequoia github page. 

### ISSUE THREAD

**Issue by 1030617255** [andreas-steigmiller/owllink-owlapi-adapter#1]
Hi! I see you id in Sequoia github page. I have a problem, I wonder if you can help me.I can not get the
jar within sbt building. would give me  your jar package after sbt building.Thank you very very much!
This is my email: liuzhao4420@outlook.com

**Comment by andreas-steigmiller** [comment]
I made the OWL API Jar Package of Sequoia available under https://www.dropbox.com/s/z62ry0dsc5xaums/Sequoia-OWL-API-fat-jar.jar?dl=0
